### PR TITLE
Json serialisation

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Thanks.  I got the basis of my objective completed using this.  See
https://github.com/jayvdb/era_data/blob/master/fetch.sh#L30

I'll be doing some analysis of the resulting data over the next few days, and unless they are bugs it would be nice to have this released.

**Comment by chfw** [comment]
Let me fix https://github.com/pyexcel/pyexcel-text/issues/8 and get a release out of it and you could then update https://github.com/jayvdb/era_data/blob/master/requirements.txt#L3

**Comment by jayvdb** [comment]
There is also a FIXME i added to the tests, but i am out of time until the weekend

**Comment by chfw** [comment]
ready to be released. let me know after you will have time to evaluate 0.1.2.

**Comment by jayvdb** [comment]
A changelog file would be helpful.

**Pull request merged**
